# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x15\x64istributed_inference\";\n\rTensorPayload\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\xd8\x01\n\x0e\x46orwardRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x12\n\nis_prefill\x18\x03 \x01(\x08\x12\x15\n\rreturn_logits\x18\x04 \x01(\x08\x12;\n\rhidden_states\x18\x05 \x01(\x0b\x32$.distributed_inference.TensorPayload\x12<\n\x0e\x61ttention_mask\x18\x06 \x01(\x0b\x32$.distributed_inference.TensorPayload\"\xa6\x01\n\x0f\x46orwardResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12;\n\rhidden_states\x18\x03 \x01(\x0b\x32$.distributed_inference.TensorPayload\x12\x34\n\x06logits\x18\x04 \x01(\x0b\x32$.distributed_inference.TensorPayload\"\x0f\n\rHealthRequest\"L\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bworker_name\x18\x02 \x01(\t\x12\x15\n\rlayer_indices\x18\x03 \x03(\x05\x32\xc2\x01\n\x0fPartitionWorker\x12X\n\x07\x46orward\x12%.distributed_inference.ForwardRequest\x1a&.distributed_inference.ForwardResponse\x12U\n\x06Health\x12$.distributed_inference.HealthRequest\x1a%.distributed_inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORPAYLOAD']._serialized_start=42
  _globals['_TENSORPAYLOAD']._serialized_end=101
  _globals['_FORWARDREQUEST']._serialized_start=104
  _globals['_FORWARDREQUEST']._serialized_end=320
  _globals['_FORWARDRESPONSE']._serialized_start=323
  _globals['_FORWARDRESPONSE']._serialized_end=489
  _globals['_HEALTHREQUEST']._serialized_start=491
  _globals['_HEALTHREQUEST']._serialized_end=506
  _globals['_HEALTHRESPONSE']._serialized_start=508
  _globals['_HEALTHRESPONSE']._serialized_end=584
  _globals['_PARTITIONWORKER']._serialized_start=587
  _globals['_PARTITIONWORKER']._serialized_end=781
# @@protoc_insertion_point(module_scope)
