# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x9a\x01\n\x0bTailRequest\x12\x14\n\x0chidden_state\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x13\n\x0bsplit_layer\x18\x05 \x01(\x05\x12\x16\n\x0e\x61ttention_mask\x18\x06 \x01(\x0c\x12\x16\n\x0emax_new_tokens\x18\x07 \x01(\x05\"_\n\x0cTailResponse\x12\x0e\n\x06logits\x18\x01 \x01(\x0c\x12\x14\n\x0clogits_shape\x18\x02 \x03(\x03\x12)\n\x07metrics\x18\x03 \x01(\x0b\x32\x18.inference.ServerMetrics\"\xa8\x01\n\rTokenResponse\x12\x10\n\x08token_id\x18\x01 \x01(\x05\x12\x12\n\ntoken_text\x18\x02 \x01(\t\x12\x16\n\x0eis_first_token\x18\x03 \x01(\x08\x12\x15\n\ris_last_token\x18\x04 \x01(\x08\x12\x17\n\x0fstep_latency_ms\x18\x05 \x01(\x02\x12)\n\x07metrics\x18\x06 \x01(\x0b\x32\x18.inference.ServerMetrics\"\xa5\x01\n\rServerMetrics\x12\x16\n\x0e\x65\x32\x65_latency_ms\x18\x01 \x01(\x02\x12\x13\n\x0btotal_flops\x18\x02 \x01(\x01\x12\x13\n\x0bpeak_mem_mb\x18\x03 \x01(\x02\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x13\n\x0bpower_state\x18\x05 \x01(\t\x12-\n\rlayer_metrics\x18\x06 \x03(\x0b\x32\x16.inference.LayerMetric\"Z\n\x0bLayerMetric\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x02\x12\r\n\x05\x66lops\x18\x03 \x01(\x01\x12\x14\n\x0cmem_delta_mb\x18\x04 \x01(\x02\"\x0f\n\rHealthRequest\"s\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x13\n\x0bsplit_layer\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x17\n\x0fgpu_mem_free_mb\x18\x05 \x01(\x02\x32\xda\x01\n\x10InferenceService\x12:\n\x07RunTail\x12\x16.inference.TailRequest\x1a\x17.inference.TailResponse\x12\x46\n\x10RunTailStreaming\x12\x16.inference.TailRequest\x1a\x18.inference.TokenResponse0\x01\x12\x42\n\x0bHealthCheck\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAILREQUEST']._serialized_start=31
  _globals['_TAILREQUEST']._serialized_end=185
  _globals['_TAILRESPONSE']._serialized_start=187
  _globals['_TAILRESPONSE']._serialized_end=282
  _globals['_TOKENRESPONSE']._serialized_start=285
  _globals['_TOKENRESPONSE']._serialized_end=453
  _globals['_SERVERMETRICS']._serialized_start=456
  _globals['_SERVERMETRICS']._serialized_end=621
  _globals['_LAYERMETRIC']._serialized_start=623
  _globals['_LAYERMETRIC']._serialized_end=713
  _globals['_HEALTHREQUEST']._serialized_start=715
  _globals['_HEALTHREQUEST']._serialized_end=730
  _globals['_HEALTHRESPONSE']._serialized_start=732
  _globals['_HEALTHRESPONSE']._serialized_end=847
  _globals['_INFERENCESERVICE']._serialized_start=850
  _globals['_INFERENCESERVICE']._serialized_end=1068
# @@protoc_insertion_point(module_scope)
